### ISSUE TITLE
I have a problems, bro

### ISSUE THREAD

**Issue by Djemchik** [Quasolaris/NewPipePlaylistExtractor#3]
Extracting Playlists...
Traceback (most recent call last):
  File "/root/NewPipePlaylistExtractor/Script/main.py", line 262, in <module>
    main(sys.argv[1])
  File "/root/NewPipePlaylistExtractor/Script/main.py", line 192, in main
    Playlists = getPlaylists(db_file)
  File "/root/NewPipePlaylistExtractor/Script/main.py", line 105, in getPlaylists
    rows = get_rows(db_file)
  File "/root/NewPipePlaylistExtractor/Script/main.py", line 88, in get_rows
    cur.execute(sqlCmds)
sqlite3.OperationalError: no such table: streams

**Comment by Quasolaris** [comment]
Can you write how you run the script, that I can replicate.

Is the path to the newpipe.db file correct? I can replicate the error when I give a wrong path as argument.

**Comment by Djemchik** [comment]
The link of my file database is here

http://file.sampo.ru/4j8375/

**Comment by Quasolaris** [comment]
I'm not downloading your file, sorry.

I tested the script with a new generated database via the newest NewPipe version and it worked fine on my machine.

The line ```sqlite3.OperationalError: no such table: streams``` tells me that it does not find any playlists in your DB-File, I can see two possible reasons for that:

- Did you extract the file?
    - The script can not extract your playlists when you give it the ```.zip``` as path, you need to give the ```newpipe.db``` as an argument.

- Maybe it could also be that you use some special characters in your playlist names?
    - It could be that the SQL-Lib I use can not handle special characters.

**Comment by Djemchik** [comment]
I am trying to download this playlist 



https://youtube.com/playlist?list=PLOAFzRws139CoGX2UvsGx5yWplrxBB6Hh

**Comment by Quasolaris** [comment]
The script is made for playlists that are created using NewPipe, means that the playlists do not share a YouTube-Link, they are locally created on your device and therefore inside the SQL database.

Can it be that you have only YouTube-created playlists saved in your NewPipe? If yes then the newpipe.db file can be empty and that is why you get that error.

To download playlists that are created using YouTube (with a YT-Account) is not possible with this script (at the moment), you could use something like [PyTube](https://pytube.io/en/latest/user/quickstart.html) or look for a YouTube downloader.
