### ISSUE TITLE
Is the cipher.py fix still working?

### ISSUE THREAD

**Issue by tsarinaspades** [Quasolaris/NewPipePlaylistExtractor#8]
Hello

I'm trying to download a playlist I created on NewPipe. I followed the Android tutorial with Termux and Pydroid 3.

Everything works except the actual files download that display an error: 

```
HTTP Error 400: Bad Request
If Error is: get_throttling_function_name: could not find match for multiple
Read the Error chapter in the README
Done!
.../0/pytube_custom $
```

I went to the README file and updated the cipher.py file through Pydroid 3.

I still get the exact same Error. 

What should I do?

I'm on Samsung S22+
Android 14
OneUi 6.1
NewPipe 27.2

**Comment by Quasolaris** [comment]
Hi @tsarinaspades 
It seems that YouTube once again changed their API (or did something other to hinder such projects like Pytube or New Pipe), maybe you can try some of the fixes that are mentioned here:

https://github.com/pytube/pytube/issues/1973

I hope this helps, I'm working on a fix (if possible) for some Pytube errors our script generates...

Cheers

**Comment by Quasolaris** [comment]
Closing this issue as it is a Pytube problem not a NewPipeExtractor one.
Will add a fix (if I find one) to the Readme.
